name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: MohitSahoo
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push changes
        uses: actions/add-and-commit@v9
        with:
          message: "Update snake animation"
          branch: main